### ISSUE TITLE
Upgrade to the OCI Format or Docker Image manifest v2, schema 2

### ISSUE THREAD

**Issue by rubens-sertage-grego-itv** [obytes/redis-browser-docker#1]
With latest Docker, when running docker-compose up with the following code:
```
  redis-browser:
    image: obytes/redis-browser:latest
    command: --url redis://redis:6379
    ports:
      - 4567:4567
    links:
      - redis
```
It fails with the error message:

> [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/obytes/redis-browser:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
